ENV: development
PORT: 3001

DATABASE_URL: "host=localhost user=postgres password=root dbname=go_backend port=5432 sslmode=disable"

JWT_SECRET: "devsecret"

AGORA:
  APP_ID: "your_agora_app_id_here"
  APP_CERTIFICATE: "your_agora_certificate_here"
  TOKEN_EXPIRY: 3600   # optional but useful, in seconds
